#define VERSION_MAJOR					3
#define VERSION_MINOR					5
#define VERSION_REVISION				0
#define VERSION_BUILD					0
#define VERSION32						((VERSION_MAJOR << 24) | (VERSION_MINOR << 16) | (VERSION_REVISION << 8) | VERSION_BUILD)

#define VER_PRODUCTVERSION_STR			"3.5"
